#!/bin/sh
HERE="$(dirname "$(readlink -f "$0")")"
export GSETTINGS_SCHEMA_DIR="$HERE/share-schemas"
export GDK_PIXBUF_MODULEDIR="$HERE/lib/gdk-pixbuf-2.0/2.10.0/loaders"
export GDK_PIXBUF_MODULE_FILE="$HERE/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache"
exec "$HERE/RemoteControl" "$@"
