#pragma once

#include <gtk/gtk.h>
#include <filesystem>
#include <deque>
#include <functional>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

class TSyncManager {
public:
    enum class ScriptType { Weapon, Class, NPC };
    TSyncManager(GtkWidget* parent, std::filesystem::path applicationDirectory, std::function<void(int, bool)> onProgress = {});
    ~TSyncManager();
    void setConnection(void* connection, const std::string& serverName);
    void showWindow();
    bool isFileSyncActive() const;

private:
    enum class SyncDirection { DownloadOnly, UploadOnly, TwoWay };
    struct Entry {
        ScriptType type = ScriptType::Weapon;
        std::string name;
        std::string image;
        std::string npcType;
        std::string level;
        int id = 0;
        std::filesystem::path relativePath;
        std::size_t localHash = 0;
        std::size_t serverHash = 0;
        int serverModified = 0;
        std::size_t pendingUploadHash = 0;
        gint64 pendingUploadUntil = 0;
    };
    struct FileEntry {
        std::string remotePath;
        std::filesystem::path relativePath;
        std::size_t localHash = 0;
        int serverSize = 0;
        int serverModified = 0;
        std::size_t pendingUploadHash = 0;
        gint64 pendingUploadUntil = 0;
    };
    struct ConfigEntry {
        std::string type;
        std::filesystem::path relativePath;
        std::size_t localHash = 0;
        std::size_t serverHash = 0;
        std::size_t pendingUploadHash = 0;
        gint64 pendingUploadUntil = 0;
    };

    static gboolean onTick(gpointer data);
    static void onChooseWorkspace(GtkButton*, gpointer data);
    static void onStart(GtkButton*, gpointer data);
    static void onStop(GtkButton*, gpointer data);
    static void onPull(GtkButton*, gpointer data);
    static void onOpenWorkspace(GtkButton*, gpointer data);
    static void onGitInitialize(GtkButton*, gpointer data);
    static void onGitCommit(GtkButton*, gpointer data);
    static void onGitPull(GtkButton*, gpointer data);
    static void onGitPush(GtkButton*, gpointer data);
    static void onImportGitKey(GtkButton*, gpointer data);
    static void onClearGitKey(GtkButton*, gpointer data);
    static void onSaveGitToken(GtkButton*, gpointer data);
    static void onClearGitToken(GtkButton*, gpointer data);
    static void onGitKeyChosen(GtkDialog*, gint response, gpointer data);
    static void onAutoCommit(GtkToggleButton*, gpointer data);
    static void onAutoPush(GtkToggleButton*, gpointer data);
    static void onAutoPull(GtkToggleButton*, gpointer data);
    static void onAutoStart(GtkToggleButton*, gpointer data);
    static void onWorkspaceChosen(GtkDialog*, gint response, gpointer data);
    static gboolean onWindowDelete(GtkWidget*, GdkEvent*, gpointer data);
    static void onFileList(const char* folder, int count, void* data);
    static void onFileRoots(int count, void* data);
    static void onFileReceived(const char* path, const void* content, int length, void* data);
    static void onServerData(const char* type, const char* content, void* data);
    static void onSyncScripts(GtkToggleButton*, gpointer data);
    static void onSyncFiles(GtkToggleButton*, gpointer data);
    static void onSyncConfig(GtkToggleButton*, gpointer data);
    static void onSyncDirectionChanged(GtkComboBox*, gpointer data);
    static void onAllowRemoteDeletes(GtkToggleButton*, gpointer data);
    static void onFileFoldersChanged(GtkEditable*, gpointer data);
    static void onFileExcludesChanged(GtkEditable*, gpointer data);
    static void onChooseFileFolders(GtkButton*, gpointer data);
    static void onFileRootsResponse(GtkDialog*, gint response, gpointer data);
    static void onFileRootExpanded(GtkTreeView*, GtkTreeIter*, GtkTreePath*, gpointer data);
    static void onFileRootCollapsed(GtkTreeView*, GtkTreeIter*, GtkTreePath*, gpointer data);
    static void onFileRootToggled(GtkCellRendererToggle*, gchar* path, gpointer data);
    static void onGitRemoteChanged(GtkEditable*, gpointer data);

    void loadConfig();
    void saveConfig() const;
    void loadManifest();
    void saveManifest() const;
    void prepareWorkspace();
    void start();
    void stop();
    void requestPull();
    void refreshCache();
    void scanLocalChanges();
    void beginScriptMetadataLookup();
    void requestNextScriptMetadataFolder();
    void applyScriptMetadata(const std::string& folder, const void* items, int count);
    void beginFilePull();
    void requestNextFileFolder();
    void requestNextFileDownload();
    bool isFileExcluded(const std::string& path) const;
    void scanLocalFiles();
    void scanLocalConfig();
    void syncConfigEntry(const std::string& type, const std::string& content);
    void syncEntry(Entry& entry, const std::string& script);
    void addOrUpdateEntry(ScriptType type, const std::string& name, int id, const std::string& image, const std::string& npcType, const std::string& level, const std::string& script);
    bool uploadEntry(Entry& entry, const std::string& script);
    bool deleteEntry(const Entry& entry);
    bool downloadsAllowed() const;
    bool uploadsAllowed() const;
    int progressPercent() const;
    std::string currentPhaseText() const;
    bool runGit(const std::vector<std::string>& arguments, std::string& output) const;
    bool configureGitRemote(std::string& output) const;
    bool storeGitKey(const std::string& content);
    bool loadGitKey(std::string& content) const;
    void clearGitKey();
    bool storeGitToken(const std::string& content);
    bool loadGitToken(std::string& content) const;
    void clearGitToken();
    void gitCommitDownloaded();
    void createWindow();
    void refreshWindow();
    void scheduleWindowRefresh();
    void showResult(const std::string& title, const std::string& message, GtkMessageType type = GTK_MESSAGE_INFO) const;
    std::filesystem::path configPath() const;
    std::filesystem::path manifestPath() const;
    std::filesystem::path absolutePath(const Entry& entry) const;
    std::string statusText() const;
    void setPhase(const std::string& value);
    void logEvent(const std::string& value);
    void showFileRoots(const std::vector<std::string>& roots);
    void requestNextFilePickerFolder();
    bool findFileRoot(const std::string& path, GtkTreeIter& result) const;

    GtkWidget* parent = nullptr;
    GtkWidget* window = nullptr;
    GtkWidget* statusLabel = nullptr;
    GtkWidget* phaseLabel = nullptr;
    GtkWidget* queueLabel = nullptr;
    GtkWidget* totalsLabel = nullptr;
    GtkWidget* activityView = nullptr;
    GtkWidget* workspaceField = nullptr;
    GtkWidget* startButton = nullptr;
    GtkWidget* stopButton = nullptr;
    GtkWidget* pullButton = nullptr;
    GtkWidget* autoCommitCheck = nullptr;
    GtkWidget* autoPushCheck = nullptr;
    GtkWidget* autoPullCheck = nullptr;
    GtkWidget* autoStartCheck = nullptr;
    GtkWidget* syncScriptsCheck = nullptr;
    GtkWidget* syncFilesCheck = nullptr;
    GtkWidget* syncConfigCheck = nullptr;
    GtkWidget* syncDirectionCombo = nullptr;
    GtkWidget* allowRemoteDeletesCheck = nullptr;
    GtkWidget* fileFoldersField = nullptr;
    GtkWidget* fileExcludesField = nullptr;
    GtkWidget* fileRootsDialog = nullptr;
    GtkTreeStore* fileRootsStore = nullptr;
    GdkPixbuf* fileRootFolderIcon = nullptr;
    GdkPixbuf* fileRootOpenFolderIcon = nullptr;
    GtkWidget* gitRemoteField = nullptr;
    GtkWidget* gitKeyLabel = nullptr;
    GtkWidget* gitTokenField = nullptr;
    std::filesystem::path applicationDirectory;
    std::filesystem::path workspace;
    void* connection = nullptr;
    std::string serverName;
    std::unordered_map<std::string, Entry> entries;
    std::unordered_map<std::string, FileEntry> fileEntries;
    std::unordered_map<std::string, ConfigEntry> configEntries;
    std::unordered_map<std::string, int> scriptModifiedTimes;
    std::deque<std::string> pendingFileFolders;
    std::deque<std::string> pendingFileDownloads;
    std::unordered_set<std::string> pendingArchiveFolders;
    std::unordered_set<std::string> archiveProbeFolders;
    std::deque<std::string> pendingScriptMetadataFolders;
    std::string activeScriptMetadataFolder;
    gint64 activeScriptMetadataStarted = 0;
    std::string activeFileFolder;
    std::string activeFileDownload;
    std::string activeFileDownloadFolder;
    gint64 activeFileDownloadStarted = 0;
    int activeFileDownloadAttempts = 0;
    long long activeFileDownloadReceived = 0;
    long long activeFileDownloadTotal = 0;
    gint64 syncStarted = 0;
    std::size_t syncWorkTotal = 0;
    std::size_t syncWorkDone = 0;
    std::unordered_set<std::string> completedSyncItems;
    std::string fileFolders;
    std::string fileExcludes;
    std::string gitRemoteUrl;
    std::string phase = "Stopped";
    std::deque<std::string> activity;
    std::size_t activitySerial = 0;
    std::size_t activityDiscarded = 0;
    std::size_t renderedActivitySerial = 0;
    std::size_t renderedActivityDiscarded = 0;
    bool choosingFileRoots = false;
    bool browsingFileRoots = false;
    bool parentVisibleBeforeFilePicker = false;
    std::string filePickerLoadingFolder;
    std::deque<std::string> pendingFilePickerFolders;
    std::vector<std::string> filePickerSelected;
    guint timer = 0;
    guint refreshSource = 0;
    gint64 nextPull = 0;
    bool manifestDirty = false;
    bool enabled = false;
    bool oneShotActive = false;
    bool progressUnseen = false;
    bool discoveringFileRoots = false;
    bool discoveringScriptMetadata = false;
    bool autoCommit = false;
    bool autoPush = false;
    bool autoPull = false;
    bool autoStart = false;
    bool syncScripts = true;
    bool syncFiles = false;
    bool syncConfig = false;
    SyncDirection syncDirection = SyncDirection::DownloadOnly;
    bool allowRemoteDeletes = false;
    int downloadedChanges = 0;
    int uploadedChanges = 0;
    std::function<void(int, bool)> onProgress;
};
