if(NOT DEFINED REMOTE_CONTROL_VERSION_HEADER OR NOT DEFINED REMOTE_CONTROL_7Z_EXECUTABLE OR NOT DEFINED REMOTE_CONTROL_7Z_SFX_MODULE OR NOT DEFINED REMOTE_CONTROL_RUNTIME_DIRECTORY OR NOT DEFINED REMOTE_CONTROL_STAGING_DIRECTORY OR NOT DEFINED REMOTE_CONTROL_OUTPUT_DIRECTORY)
    message(FATAL_ERROR "Remote Control single-file packaging arguments are incomplete")
endif()
file(READ "${REMOTE_CONTROL_VERSION_HEADER}" version_header)
string(REGEX MATCH "REMOTE_CONTROL_BUILD_VERSION \"([^\"]+)\"" version_match "${version_header}")
if(NOT CMAKE_MATCH_1)
    message(FATAL_ERROR "Remote Control build version was not found")
endif()
set(version "${CMAKE_MATCH_1}")
set(payload "${REMOTE_CONTROL_STAGING_DIRECTORY}/RemoteControlPayload.7z")
set(config "${REMOTE_CONTROL_STAGING_DIRECTORY}/RemoteControlSfxConfig.txt")
set(output "${REMOTE_CONTROL_OUTPUT_DIRECTORY}/GScript.RC-${version}.exe")
set(payload_root "${REMOTE_CONTROL_STAGING_DIRECTORY}/RemoteControlSfxRoot")
file(REMOVE "${payload}" "${config}" "${output}")
file(REMOVE_RECURSE "${payload_root}")
file(MAKE_DIRECTORY "${payload_root}/RC")
file(GLOB runtime_entries LIST_DIRECTORIES true "${REMOTE_CONTROL_RUNTIME_DIRECTORY}/*")
foreach(runtime_entry IN LISTS runtime_entries)
    file(COPY "${runtime_entry}" DESTINATION "${payload_root}/RC")
endforeach()
execute_process(COMMAND "${REMOTE_CONTROL_7Z_EXECUTABLE}" a -t7z "${payload}" "RC/*" -mx=9 -mmt=on WORKING_DIRECTORY "${payload_root}" RESULT_VARIABLE archive_result OUTPUT_QUIET ERROR_VARIABLE archive_error)
if(NOT archive_result EQUAL 0)
    file(REMOVE_RECURSE "${payload_root}")
    message(FATAL_ERROR "Unable to create the single-file payload: ${archive_error}")
endif()
file(WRITE "${config}" ";!@Install@!UTF-8!\nGUIMode=\"2\"\nOverwriteMode=\"1\"\nInstallPath=\".\"\nRunProgram=\"RC\\RemoteControl.exe\"\n;!@InstallEnd@!\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -E cat "${REMOTE_CONTROL_7Z_SFX_MODULE}" "${config}" "${payload}" OUTPUT_FILE "${output}" RESULT_VARIABLE sfx_result ERROR_VARIABLE sfx_error)
if(NOT sfx_result EQUAL 0)
    file(REMOVE_RECURSE "${payload_root}")
    message(FATAL_ERROR "Unable to assemble the single-file executable: ${sfx_error}")
endif()
file(SIZE "${output}" output_size)
file(GLOB runtime_entries LIST_DIRECTORIES true "${REMOTE_CONTROL_RUNTIME_DIRECTORY}/*")
foreach(runtime_entry IN LISTS runtime_entries)
    if(NOT "${runtime_entry}" STREQUAL "${output}")
        file(REMOVE_RECURSE "${runtime_entry}")
    endif()
endforeach()
file(REMOVE "${payload}" "${config}")
file(REMOVE_RECURSE "${payload_root}")
message(STATUS "Created ${output} (${output_size} bytes)")
