if(NOT DEFINED OUTPUT)
    message(FATAL_ERROR "OUTPUT is required")
endif()
get_filename_component(output_directory "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${output_directory}")
string(TIMESTAMP build_date "%Y/%m/%d")
set(content "#pragma once\n#define REMOTE_CONTROL_BUILD_DATE \"${build_date}\"\n")
if(NOT EXISTS "${OUTPUT}")
    file(WRITE "${OUTPUT}" "${content}")
else()
    file(READ "${OUTPUT}" previous_content)
    if(NOT previous_content STREQUAL content)
        file(WRITE "${OUTPUT}" "${content}")
    endif()
endif()
