if(NOT DEFINED OUTPUT)
    message(FATAL_ERROR "OUTPUT is required")
endif()
if(NOT DEFINED SOURCE_DIR)
    message(FATAL_ERROR "SOURCE_DIR is required")
endif()
get_filename_component(output_directory "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${output_directory}")
string(TIMESTAMP build_date "%Y/%m/%d")
string(TIMESTAMP build_year "%Y")
execute_process(COMMAND git -C "${SOURCE_DIR}" rev-list --count HEAD RESULT_VARIABLE git_result OUTPUT_VARIABLE build_number OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
if(git_result EQUAL 0 AND build_number MATCHES "^[0-9]+$")
    set(build_version "0.1.0.${build_number}")
else()
    set(build_number 0)
    set(build_version "0.1.0.0")
endif()
set(content "#pragma once\n#define REMOTE_CONTROL_BUILD_DATE \"${build_date}\"\n#define REMOTE_CONTROL_BUILD_YEAR \"${build_year}\"\n#define REMOTE_CONTROL_BUILD_NUMBER ${build_number}\n#define REMOTE_CONTROL_BUILD_VERSION \"${build_version}\"\n")
if(NOT EXISTS "${OUTPUT}")
    file(WRITE "${OUTPUT}" "${content}")
else()
    file(READ "${OUTPUT}" previous_content)
    if(NOT previous_content STREQUAL content)
        file(WRITE "${OUTPUT}" "${content}")
    endif()
endif()
